# Generated by Django 4.1.4 on 2022-12-13 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('rifle', 'Rifle'), ('pistol', 'Pistol'), ('knife', 'Knife')], max_length=6)),
                ('price', models.PositiveIntegerField()),
                ('picture', models.ImageField(upload_to='mediafiles/guns/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
