# Generated by Django 4.1.4 on 2022-12-13 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('recoil_case', 'Recoil Case'), ('dreams_and_nightmares', 'Dreams and Nightmares'), ('clutch_case', 'Clutch Case'), ('glove_case', 'Glove Case'), ('gamma_2_case', 'Gamma 2 Case'), ('fracture_case', 'Fracture Case'), ('revolver_case', 'Revolver Case'), ('snakebite_case', 'Snakebite Case')], max_length=21)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('picture', models.ImageField(upload_to='mediafiles/containers/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('side', models.CharField(choices=[('t_side', 'T Side'), ('ct_side', 'CT Side')], max_length=7)),
                ('picture', models.ImageField(upload_to='mediafiles/agents/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
