# Generated by Django 4.1.4 on 2022-12-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0002_container_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='mediafiles/agents/'),
        ),
        migrations.AlterField(
            model_name='container',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='mediafiles/containers/'),
        ),
        migrations.AlterField(
            model_name='guns',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='mediafiles/guns/'),
        ),
    ]
