# Generated by Django 4.1.4 on 2022-12-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0005_alter_container_user_alter_guns_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='agents/'),
        ),
        migrations.AlterField(
            model_name='container',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='containers/'),
        ),
        migrations.AlterField(
            model_name='guns',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='guns/'),
        ),
    ]
