# Generated by Django 4.1.4 on 2022-12-11 16:46

from django.db import migrations
import finalExamProject.accounts.managers


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mainuser',
            managers=[
                ('objects', finalExamProject.accounts.managers.MainUserManager()),
            ],
        ),
    ]
