# Generated by Django 4.1.4 on 2022-12-17 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0004_alter_profile_picture'),
        ('common', '0002_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='profile',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='profile_app.profile'),
            preserve_default=False,
        ),
    ]
