# Generated by Django 4.1.4 on 2022-12-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0004_alter_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_signed',
            field=models.BooleanField(default=False),
        ),
    ]
